//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.13 at 01:48:31 PM CET 
//


package com.blog.samples.webservices.personservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.blog.samples.webservices.person.Person;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codeRetour" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PersonInfos" type="{http://person.webservices.samples.blog.com}Person"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codeRetour",
    "personInfos"
})
@XmlRootElement(name = "PersonInfosResponse")
public class PersonInfosResponse {

    @XmlElement(required = true)
    protected String codeRetour;
    @XmlElement(name = "PersonInfos", required = true)
    protected Person personInfos;

    /**
     * Gets the value of the codeRetour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeRetour() {
        return codeRetour;
    }

    /**
     * Sets the value of the codeRetour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeRetour(String value) {
        this.codeRetour = value;
    }

    /**
     * Gets the value of the personInfos property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPersonInfos() {
        return personInfos;
    }

    /**
     * Sets the value of the personInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPersonInfos(Person value) {
        this.personInfos = value;
    }

}
